### ISSUE TITLE
Spinning thinking/hmmspin attribution

### ISSUE THREAD

**Issue by KubeRoot** [Kiplacon/EmotesAndSpeechBubbles#1]
Hello, I believe I'm the author of the spinning thinking emoji you included in your mod, originally published [here](https://www.reddit.com/r/blender/comments/5v3f5u/blender_render_triple_thinking/).
While the resolution is too low to say with full confidence, since I've seen other versions, the others I've seen don't have curvature on the hands which seems to be visible on the included files.

If you can verify this, I'd like to be credited, and I give you permission to use my animation in the mod.

On a side-note, I'd recommend you include a license in the repository itself, as well as licenses for individual sets of images.

EDIT: If you'd like, I could try to find the original files, which should have transparency, and make a spritesheet out of them.

**Comment by Kiplacon** [comment]
The link for the gif I found off google is this one https://tenor.com/view/emoji-hmm-think-confused-gif-15510400
which I would say definitely looks the same as yours. I'll add the attribution to the mod page, thank you for giving me permission to use it 😀. Is there a specific name/link you'd like me to use referring to you? Also if you could help me out, I'm not really familiar with what types of licenses there are or how to organize them. Do you know how I can find what license a graphic has? Would I need a license in the root folder for each image?

**Comment by KubeRoot** [comment]
As for referring to me, either `KubeRoot`, `KubeRoot#0001`, or maybe a link to my github profile is fine.

As for the licenses... Legal stuff can be complicated, I am not a lawyer and this is not legal advice. Because apparently saying this is a thing. *Yeaah.*
I don't know any of this stuff for sure, and I had to look it up.

Your mod has its license set as [MIT](https://choosealicense.com/licenses/mit/) on the Factorio mod portal. To my knowledge, it basically allows anybody to use your code for anything as long as they don't change the license.
The common convention is to put the license for the whole project in the root of the directory in a file named `LICENSE.md`, github should have a button somewhere to do that automatically with one of the common licenses.

For individual images, if you want to do this legally, you need to find the license for each image from some person/entity that has legal rights to the actual image. This means if you just browse tenor, the image was likely reuploaded there by some random person without crediting the author or including the license... So you'd really have to go searching across the internet to try to find the original creator. There's no easy way to do this for arbitrary images, the only way would be to only use images that come with a license in the first place.

As for actually including the licenses for individual images, from what I can tell, there's no real rules about this. One way to do it is to include a `LICENSE-[image filename].md` file for each image, next to the image itself, containing the original license. Maybe it'd be fine to have a file listing which images are licensed under which license, to avoid duplicating them. Maybe you could put images from each source in a different directory, and include a separate `LICENSE.md` in each subfolder with images.

**Comment by Kiplacon** [comment]
I added your name to the mod page as well as the other sources I could find for each gif. I also copied the names to the GitHub readme. I'll have to think about how to handle the licenses
